version: "3.4"

networks:
  db-network:
    driver: bridge
  server-network:
    driver: bridge

services:
  db:
    container_name: thesafestbank-db
    image: postgres:16.1-alpine3.18
    environment:
      - POSTGRES_USER=thesafestbank-server
      - POSTGRES_PASSWORD=Vch6mSw0rKjcGlBZCbvu
      - POSTGRES_DB=thesafestbankdb
    restart: always
    ports:
      - "5432:5432" ##TODO - USUN PERFORACJE
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    networks:
      - db-network

  server:
    container_name: thesafestbank-server
    image: thesafestbank-server
    environment:
      - ASPNETCORE_ENVIRONMENT=Production #TODO - zmienic na Production
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/certificate.crt
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/https/certificate.key
      - KEY=bA3EOFZKtlQvsGkM
      - DB_CONNECTION_STRING=Server=thesafestbank-db;Database=thesafestbankdb;Port=5432;User Id=thesafestbank-server;Password=Vch6mSw0rKjcGlBZCbvu;
    build: ./SafestBankServer
    depends_on:
      - db
    ports:
      - "5001:443" ##TODO - USUN PERFORACJE
    volumes:
      - ./certificates:/https
    networks:
      - db-network
      - server-network

  reverse-proxy:
    container_name: thesafestbank-reverse-proxy
    image: nginx:1.23.3
    ports:
      - "5000:443"
    depends_on:
      - server
    volumes:
      - ./certificates:/etc/ssl/certs
      - ./reverse-proxy-conf:/etc/nginx
    networks:
      - server-network

  client:
    container_name: thesafestbank-client
    image: thesafestbank-client
    build: ./safest-bank-client
    depends_on:
      - server
    volumes:
      - ./certificates:/etc/ssl/certs
    ports:
      - "80:80"
      - "443:443"

volumes:
  dbdata:
  certificates:
  reverse-proxy-conf:
