version: "3.4"

networks:
  safest-network:
    driver: bridge

services:
  db:
    container_name: thesafestbank-db
    image: postgres:16.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=thesafestbankdb
    restart: always
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432" #TODO - USUN ZEWNETRZNY DOSTEP
    networks:
      - safest-network

  server:
    container_name: thesafebank-server
    image: thesafestbank-server
    environment:
      - ASPNETCORE_ENVIRONMENT=Development #TODO - zmienic na Production
      - ASPNETCORE_URLS=http://+:80
    build: ./SafestBankServer
    depends_on:
      - db
    ports:
      - "5000:80"
    networks:
      - safest-network

volumes:
  dbdata:
