version: "3.4"

networks:
  safest-network:
    driver: bridge

services:
  db:
    container_name: thesafestbank-db
    image: postgres:16.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=thesafestbankdb
    restart: always
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    networks:
      - safest-network

  server:
    container_name: thesafestbank-server
    image: thesafestbank-server
    environment:
      - ASPNETCORE_ENVIRONMENT=Development #TODO - zmienic na Production
      - ASPNETCORE_URLS=http://+:80
    build: ./SafestBankServer
    depends_on:
      - db
    ports:
      - "5000:80"
    networks:
      - safest-network

  client:
    container_name: thesafestbank-client
    image: thesafestbank-client
    environment:
      - HTTPS=true
      - SSL_CRT_FILE=/etc/ssl/certs/certificate.crt
      - SSL_KEY_FILE=/etc/ssl/certs/certificate.key
    build: ./safest-bank-client
    depends_on:
      - server
    volumes:
      - ./certificates:/etc/ssl/certs
    ports:
      - "3000:3000"

volumes:
  dbdata:
  certificates:
