// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SafestBankServer.Infrastructure.EF.Contexts;

#nullable disable

namespace SafestBankServer.Infrastructure.Migrations
{
    [DbContext(typeof(SafestBankDbContext))]
    [Migration("20240121152002_ProductionMigration")]
    partial class ProductionMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SafestBankServer.Core.Auth.Passwords.PartialPassword", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BankClientId")
                        .HasColumnType("uuid");

                    b.Property<int[]>("Mask")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<byte[]>("PartialPasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("PasswordStatus")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("BankClientId");

                    b.ToTable("PartialPasswords");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e0552eb4-2b5b-4e25-beff-46550cfb0e8f"),
                            BankClientId = new Guid("b4092f92-57fd-4032-b73d-e407036d3abf"),
                            Mask = new[] { 1, 7, 9, 10, 13 },
                            PartialPasswordHash = new byte[] { 140, 249, 93, 214 },
                            PasswordStatus = 2,
                            Salt = new byte[] { 34, 7, 1, 196 }
                        },
                        new
                        {
                            Id = new Guid("e2635041-7598-4ca2-a072-2a8c4f460f10"),
                            BankClientId = new Guid("b4092f92-57fd-4032-b73d-e407036d3abf"),
                            Mask = new[] { 1, 2, 8, 10, 12 },
                            PartialPasswordHash = new byte[] { 150, 45, 106, 63 },
                            PasswordStatus = 1,
                            Salt = new byte[] { 182, 194, 163, 105 }
                        },
                        new
                        {
                            Id = new Guid("96d80488-8d84-4f7d-ac0d-4b7a9177001e"),
                            BankClientId = new Guid("b4092f92-57fd-4032-b73d-e407036d3abf"),
                            Mask = new[] { 0, 3, 10, 13, 14 },
                            PartialPasswordHash = new byte[] { 111, 48, 40, 86 },
                            PasswordStatus = 1,
                            Salt = new byte[] { 37, 185, 0, 222 }
                        },
                        new
                        {
                            Id = new Guid("ce058595-2184-466f-93d2-ecd6a60499ff"),
                            BankClientId = new Guid("b4092f92-57fd-4032-b73d-e407036d3abf"),
                            Mask = new[] { 0, 2, 3, 14, 15 },
                            PartialPasswordHash = new byte[] { 111, 233, 146, 141 },
                            PasswordStatus = 1,
                            Salt = new byte[] { 65, 143, 165, 34 }
                        },
                        new
                        {
                            Id = new Guid("4adefcd8-92b2-4432-a7ce-7dac026553d0"),
                            BankClientId = new Guid("b4092f92-57fd-4032-b73d-e407036d3abf"),
                            Mask = new[] { 4, 6, 10, 12, 13 },
                            PartialPasswordHash = new byte[] { 221, 51, 74, 80 },
                            PasswordStatus = 1,
                            Salt = new byte[] { 125, 212, 143, 233 }
                        },
                        new
                        {
                            Id = new Guid("89d9b9b7-d235-4985-b3cf-ed9dd997be00"),
                            BankClientId = new Guid("b4092f92-57fd-4032-b73d-e407036d3abf"),
                            Mask = new[] { 0, 4, 7, 14, 15 },
                            PartialPasswordHash = new byte[] { 48, 88, 140, 186 },
                            PasswordStatus = 1,
                            Salt = new byte[] { 175, 217, 26, 178 }
                        },
                        new
                        {
                            Id = new Guid("9a10966c-e728-4171-ad32-f435b12ca91a"),
                            BankClientId = new Guid("b4092f92-57fd-4032-b73d-e407036d3abf"),
                            Mask = new[] { 0, 1, 6, 8, 11 },
                            PartialPasswordHash = new byte[] { 71, 45, 53, 50 },
                            PasswordStatus = 1,
                            Salt = new byte[] { 0, 105, 93, 31 }
                        },
                        new
                        {
                            Id = new Guid("a234a513-9a71-490d-8abe-88da7909a396"),
                            BankClientId = new Guid("b4092f92-57fd-4032-b73d-e407036d3abf"),
                            Mask = new[] { 5, 6, 9, 12, 15 },
                            PartialPasswordHash = new byte[] { 83, 122, 128, 174 },
                            PasswordStatus = 1,
                            Salt = new byte[] { 255, 90, 36, 59 }
                        },
                        new
                        {
                            Id = new Guid("dfe9818b-fb71-44e6-b5c5-60355c76542b"),
                            BankClientId = new Guid("b4092f92-57fd-4032-b73d-e407036d3abf"),
                            Mask = new[] { 2, 6, 12, 14, 15 },
                            PartialPasswordHash = new byte[] { 193, 123, 54, 89 },
                            PasswordStatus = 1,
                            Salt = new byte[] { 218, 81, 68, 104 }
                        },
                        new
                        {
                            Id = new Guid("ef48b8ce-1693-4f99-8152-b75f72ec6f2c"),
                            BankClientId = new Guid("b4092f92-57fd-4032-b73d-e407036d3abf"),
                            Mask = new[] { 3, 5, 10, 12, 15 },
                            PartialPasswordHash = new byte[] { 201, 60, 26, 226 },
                            PasswordStatus = 1,
                            Salt = new byte[] { 151, 110, 54, 237 }
                        },
                        new
                        {
                            Id = new Guid("97b89af3-2501-4ef9-9a6b-b511510ddda6"),
                            BankClientId = new Guid("b216e9bd-4cc3-429b-b1cb-f11f673faa0d"),
                            Mask = new[] { 2, 3, 6, 9, 10 },
                            PartialPasswordHash = new byte[] { 201, 84, 132, 39 },
                            PasswordStatus = 2,
                            Salt = new byte[] { 137, 76, 252, 26 }
                        },
                        new
                        {
                            Id = new Guid("04918818-b483-4750-8742-43bb050a74f9"),
                            BankClientId = new Guid("b216e9bd-4cc3-429b-b1cb-f11f673faa0d"),
                            Mask = new[] { 2, 7, 9, 10, 14 },
                            PartialPasswordHash = new byte[] { 60, 88, 123, 60 },
                            PasswordStatus = 1,
                            Salt = new byte[] { 179, 81, 122, 213 }
                        },
                        new
                        {
                            Id = new Guid("aa10adf5-1335-44bf-955b-e2a83ff93c9a"),
                            BankClientId = new Guid("b216e9bd-4cc3-429b-b1cb-f11f673faa0d"),
                            Mask = new[] { 1, 4, 9, 11, 15 },
                            PartialPasswordHash = new byte[] { 54, 180, 59, 61 },
                            PasswordStatus = 1,
                            Salt = new byte[] { 255, 198, 4, 8 }
                        },
                        new
                        {
                            Id = new Guid("c2142a5d-1238-449c-94a4-bbdfa20ee4b8"),
                            BankClientId = new Guid("b216e9bd-4cc3-429b-b1cb-f11f673faa0d"),
                            Mask = new[] { 0, 2, 6, 10, 11 },
                            PartialPasswordHash = new byte[] { 77, 17, 59, 163 },
                            PasswordStatus = 1,
                            Salt = new byte[] { 188, 23, 21, 99 }
                        },
                        new
                        {
                            Id = new Guid("7d1a55de-dda9-4fd9-8388-ae04bc5dc8ea"),
                            BankClientId = new Guid("b216e9bd-4cc3-429b-b1cb-f11f673faa0d"),
                            Mask = new[] { 7, 9, 10, 11, 14 },
                            PartialPasswordHash = new byte[] { 168, 128, 105, 180 },
                            PasswordStatus = 1,
                            Salt = new byte[] { 144, 148, 244, 116 }
                        },
                        new
                        {
                            Id = new Guid("dc4d15f1-5550-4683-a6f4-f7a54992c121"),
                            BankClientId = new Guid("b216e9bd-4cc3-429b-b1cb-f11f673faa0d"),
                            Mask = new[] { 9, 11, 12, 13, 15 },
                            PartialPasswordHash = new byte[] { 29, 59, 100, 63 },
                            PasswordStatus = 1,
                            Salt = new byte[] { 164, 132, 206, 65 }
                        },
                        new
                        {
                            Id = new Guid("1888cdc2-8a0b-4b7f-bd3d-f50692076af6"),
                            BankClientId = new Guid("b216e9bd-4cc3-429b-b1cb-f11f673faa0d"),
                            Mask = new[] { 1, 4, 6, 9, 15 },
                            PartialPasswordHash = new byte[] { 119, 122, 206, 88 },
                            PasswordStatus = 1,
                            Salt = new byte[] { 119, 210, 86, 227 }
                        },
                        new
                        {
                            Id = new Guid("180bf7bf-b477-439c-917e-80f98f8ccf63"),
                            BankClientId = new Guid("b216e9bd-4cc3-429b-b1cb-f11f673faa0d"),
                            Mask = new[] { 0, 4, 5, 10, 15 },
                            PartialPasswordHash = new byte[] { 77, 23, 201, 230 },
                            PasswordStatus = 1,
                            Salt = new byte[] { 58, 10, 104, 67 }
                        },
                        new
                        {
                            Id = new Guid("9a240026-5254-40ab-b486-ca744ecf8493"),
                            BankClientId = new Guid("b216e9bd-4cc3-429b-b1cb-f11f673faa0d"),
                            Mask = new[] { 5, 6, 10, 11, 15 },
                            PartialPasswordHash = new byte[] { 94, 27, 100, 235 },
                            PasswordStatus = 1,
                            Salt = new byte[] { 136, 157, 151, 139 }
                        },
                        new
                        {
                            Id = new Guid("08c2aade-3a81-49a1-9d8f-123ab2a8564c"),
                            BankClientId = new Guid("b216e9bd-4cc3-429b-b1cb-f11f673faa0d"),
                            Mask = new[] { 0, 4, 8, 12, 14 },
                            PartialPasswordHash = new byte[] { 119, 63, 194, 172 },
                            PasswordStatus = 1,
                            Salt = new byte[] { 20, 74, 170, 63 }
                        },
                        new
                        {
                            Id = new Guid("d4413960-699c-405e-98d2-b6d63ae3794e"),
                            BankClientId = new Guid("03a8dd46-180f-415e-80d0-3c7a5e9b3750"),
                            Mask = new[] { 4, 6, 7, 8, 12 },
                            PartialPasswordHash = new byte[] { 130, 102, 248, 69 },
                            PasswordStatus = 2,
                            Salt = new byte[] { 92, 96, 54, 81 }
                        },
                        new
                        {
                            Id = new Guid("91216156-3bc8-4849-92e3-63d0cf2db86e"),
                            BankClientId = new Guid("03a8dd46-180f-415e-80d0-3c7a5e9b3750"),
                            Mask = new[] { 5, 6, 8, 12, 14 },
                            PartialPasswordHash = new byte[] { 0, 249, 135, 47 },
                            PasswordStatus = 1,
                            Salt = new byte[] { 246, 202, 127, 231 }
                        },
                        new
                        {
                            Id = new Guid("fa57b2a3-1454-49cf-83e6-8654da665767"),
                            BankClientId = new Guid("03a8dd46-180f-415e-80d0-3c7a5e9b3750"),
                            Mask = new[] { 0, 3, 4, 10, 15 },
                            PartialPasswordHash = new byte[] { 177, 100, 199, 111 },
                            PasswordStatus = 1,
                            Salt = new byte[] { 18, 178, 232, 88 }
                        },
                        new
                        {
                            Id = new Guid("6e070a07-6faf-44ed-b4b1-0b827a8963dc"),
                            BankClientId = new Guid("03a8dd46-180f-415e-80d0-3c7a5e9b3750"),
                            Mask = new[] { 9, 10, 12, 14, 15 },
                            PartialPasswordHash = new byte[] { 102, 182, 100, 149 },
                            PasswordStatus = 1,
                            Salt = new byte[] { 231, 174, 7, 252 }
                        },
                        new
                        {
                            Id = new Guid("3fe63246-342c-44a3-987e-633575c3acc3"),
                            BankClientId = new Guid("03a8dd46-180f-415e-80d0-3c7a5e9b3750"),
                            Mask = new[] { 2, 4, 6, 9, 14 },
                            PartialPasswordHash = new byte[] { 137, 243, 165, 119 },
                            PasswordStatus = 1,
                            Salt = new byte[] { 60, 223, 72, 87 }
                        },
                        new
                        {
                            Id = new Guid("16fa8c47-bb88-4b5c-992b-81167ef5910d"),
                            BankClientId = new Guid("03a8dd46-180f-415e-80d0-3c7a5e9b3750"),
                            Mask = new[] { 0, 1, 2, 4, 8 },
                            PartialPasswordHash = new byte[] { 206, 120, 244, 104 },
                            PasswordStatus = 1,
                            Salt = new byte[] { 102, 47, 59, 74 }
                        },
                        new
                        {
                            Id = new Guid("ef27f363-bdb5-46e1-ac31-48b8cef320ae"),
                            BankClientId = new Guid("03a8dd46-180f-415e-80d0-3c7a5e9b3750"),
                            Mask = new[] { 3, 6, 8, 11, 15 },
                            PartialPasswordHash = new byte[] { 65, 90, 3, 89 },
                            PasswordStatus = 1,
                            Salt = new byte[] { 178, 97, 247, 164 }
                        },
                        new
                        {
                            Id = new Guid("3dc9ec29-4f75-4ce1-b5d7-00ba2f301c10"),
                            BankClientId = new Guid("03a8dd46-180f-415e-80d0-3c7a5e9b3750"),
                            Mask = new[] { 0, 1, 5, 6, 7 },
                            PartialPasswordHash = new byte[] { 37, 254, 87, 55 },
                            PasswordStatus = 1,
                            Salt = new byte[] { 235, 184, 220, 180 }
                        },
                        new
                        {
                            Id = new Guid("9d29e5ca-230b-427e-9f0e-4fe2119a549b"),
                            BankClientId = new Guid("03a8dd46-180f-415e-80d0-3c7a5e9b3750"),
                            Mask = new[] { 1, 5, 13, 14, 15 },
                            PartialPasswordHash = new byte[] { 146, 245, 163, 13 },
                            PasswordStatus = 1,
                            Salt = new byte[] { 158, 247, 58, 15 }
                        },
                        new
                        {
                            Id = new Guid("8aa11fd3-51a6-49f4-97bf-401cd02bb824"),
                            BankClientId = new Guid("03a8dd46-180f-415e-80d0-3c7a5e9b3750"),
                            Mask = new[] { 7, 9, 12, 14, 15 },
                            PartialPasswordHash = new byte[] { 53, 5, 173, 153 },
                            PasswordStatus = 1,
                            Salt = new byte[] { 120, 6, 55, 239 }
                        });
                });

            modelBuilder.Entity("SafestBankServer.Core.Client.BankClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<string>("ClientNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdentityCardId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastPasswordResetRequestTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LoginAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PESEL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PasswordResetAttempts")
                        .HasColumnType("integer");

                    b.Property<byte[]>("PasswordResetTokenHash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BankClients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b4092f92-57fd-4032-b73d-e407036d3abf"),
                            AccountNumber = "12345678901234567890123456",
                            AddressId = new Guid("b24cfa60-0786-43f5-b0af-454bb48b9b4f"),
                            Balance = 1000.0m,
                            ClientNumber = "123456789012",
                            Email = "sekula.sebastian.kontakt@gmail.com",
                            IdentityCardId = new Guid("0743407a-05c6-462c-bc59-bf4c791d28eb"),
                            IsBlocked = false,
                            LoginAttempts = 0,
                            Name = "Sebastian",
                            PESEL = "kiFZ9Vuou0loCNeWZ1M5Pg==",
                            PasswordResetAttempts = 0,
                            Salt = new byte[] { 29, 36, 114, 132, 62, 241, 164, 14, 149, 188, 63, 9, 230, 133, 118, 69 },
                            Surname = "Sekula"
                        },
                        new
                        {
                            Id = new Guid("b216e9bd-4cc3-429b-b1cb-f11f673faa0d"),
                            AccountNumber = "22345678901234567890123456",
                            AddressId = new Guid("8314e254-d65d-418a-9384-e3f138d2c44c"),
                            Balance = 1000.0m,
                            ClientNumber = "223456789012",
                            Email = "bob.bobkins@gmail.com",
                            IdentityCardId = new Guid("599d5e6d-bb55-42b7-9a9a-821f9571184c"),
                            IsBlocked = false,
                            LoginAttempts = 0,
                            Name = "Bob",
                            PESEL = "qyqhwpiQWlgb3K/nbDadCQ==",
                            PasswordResetAttempts = 0,
                            Salt = new byte[] { 51, 210, 119, 33, 201, 91, 29, 123, 52, 203, 155, 152, 97, 33, 152, 139 },
                            Surname = "Bobkins"
                        },
                        new
                        {
                            Id = new Guid("03a8dd46-180f-415e-80d0-3c7a5e9b3750"),
                            AccountNumber = "32345678901234567890123456",
                            AddressId = new Guid("61bfbb5a-4ee5-444a-9e04-e7aaf4472d5f"),
                            Balance = 1000.0m,
                            ClientNumber = "323456789012",
                            Email = "scotty123@gmail.com",
                            IdentityCardId = new Guid("5647486d-1526-4671-8137-6a20c77a814e"),
                            IsBlocked = false,
                            LoginAttempts = 0,
                            Name = "Scott",
                            PESEL = "FfOhfvnCQH3oDkgJM7fM/A==",
                            PasswordResetAttempts = 0,
                            Salt = new byte[] { 34, 30, 91, 238, 72, 248, 254, 89, 68, 93, 17, 250, 60, 82, 251, 208 },
                            Surname = "Scottkins"
                        });
                });

            modelBuilder.Entity("SafestBankServer.Core.Client.Data.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BankClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BankClientId")
                        .IsUnique();

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b24cfa60-0786-43f5-b0af-454bb48b9b4f"),
                            BankClientId = new Guid("b4092f92-57fd-4032-b73d-e407036d3abf"),
                            City = "4qFIWfcFUIKBRGpy+b2iJg==",
                            Country = "Poland",
                            HouseNumber = "ngq0Jt0InNy9g+hITQESCw==",
                            Street = "4IceSwS9SsG10rzss0mAxQ==",
                            ZipCode = "XlieGi2Ixh1BiluN3pE32A=="
                        },
                        new
                        {
                            Id = new Guid("8314e254-d65d-418a-9384-e3f138d2c44c"),
                            BankClientId = new Guid("b216e9bd-4cc3-429b-b1cb-f11f673faa0d"),
                            City = "Vbn7s5StymHZbBWa9Cgpkg==",
                            Country = "Poland",
                            HouseNumber = "atp/SNeKi9yptW1vOQw9eQ==",
                            Street = "jbw6JMH1jZmcbpXyGJoGsA==",
                            ZipCode = "7Tcj33TdENeQc6Wm+bmvBw=="
                        },
                        new
                        {
                            Id = new Guid("61bfbb5a-4ee5-444a-9e04-e7aaf4472d5f"),
                            BankClientId = new Guid("03a8dd46-180f-415e-80d0-3c7a5e9b3750"),
                            City = "B9f+T8voSnGBWqHXo9HLJA==",
                            Country = "Poland",
                            HouseNumber = "y+HDXbYIpnMP0A7JZEyOxg==",
                            Street = "qgoIc4Y38u4wskOOZ3QBiA==",
                            ZipCode = "zynqUtQL9YHg4ATA3/F0tQ=="
                        });
                });

            modelBuilder.Entity("SafestBankServer.Core.Client.Data.IdentityCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BankClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("CountryOfIssue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BankClientId")
                        .IsUnique();

                    b.ToTable("IdentityCards");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0743407a-05c6-462c-bc59-bf4c791d28eb"),
                            BankClientId = new Guid("b4092f92-57fd-4032-b73d-e407036d3abf"),
                            CountryOfIssue = "Poland",
                            Number = "NnY5mgee5nCi2nlaSR9UbQ==",
                            Serie = "gcPmZpxpoQN6CNSiiS99KQ==",
                            Type = "nESIu1Y4omSZIk+/UrjffClK+CSdXSjx7OcIDZwMAyM="
                        },
                        new
                        {
                            Id = new Guid("599d5e6d-bb55-42b7-9a9a-821f9571184c"),
                            BankClientId = new Guid("b216e9bd-4cc3-429b-b1cb-f11f673faa0d"),
                            CountryOfIssue = "Poland",
                            Number = "8jekknPdaXFow7ktFcpviQ==",
                            Serie = "vLDAxeWieYMYq6qvfU7Lcg==",
                            Type = "TcoDlo5j9l4A+CZ84/L3QTAMfE0BuPVHd+TUp71OTQc="
                        },
                        new
                        {
                            Id = new Guid("5647486d-1526-4671-8137-6a20c77a814e"),
                            BankClientId = new Guid("03a8dd46-180f-415e-80d0-3c7a5e9b3750"),
                            CountryOfIssue = "Poland",
                            Number = "gFYhHo6eq3xxJNC64UxD7A==",
                            Serie = "jW8pOz5YQunDmkMWdVyZGQ==",
                            Type = "BMtjDY6JrkHdJRjMhVEncyCTgznmG6KwxuOhHuW9sVM="
                        });
                });

            modelBuilder.Entity("SafestBankServer.Core.Transaction.ClientTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("BankClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("RecipientAccountNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecipientSurname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenderAccountNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenderSurname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BankClientId");

                    b.ToTable("ClientTransactions");
                });

            modelBuilder.Entity("SafestBankServer.Core.Auth.Passwords.PartialPassword", b =>
                {
                    b.HasOne("SafestBankServer.Core.Client.BankClient", null)
                        .WithMany("PartialPasswords")
                        .HasForeignKey("BankClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SafestBankServer.Core.Client.Data.Address", b =>
                {
                    b.HasOne("SafestBankServer.Core.Client.BankClient", null)
                        .WithOne("Address")
                        .HasForeignKey("SafestBankServer.Core.Client.Data.Address", "BankClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SafestBankServer.Core.Client.Data.IdentityCard", b =>
                {
                    b.HasOne("SafestBankServer.Core.Client.BankClient", null)
                        .WithOne("IdentityCard")
                        .HasForeignKey("SafestBankServer.Core.Client.Data.IdentityCard", "BankClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SafestBankServer.Core.Transaction.ClientTransaction", b =>
                {
                    b.HasOne("SafestBankServer.Core.Client.BankClient", null)
                        .WithMany("Transactions")
                        .HasForeignKey("BankClientId");
                });

            modelBuilder.Entity("SafestBankServer.Core.Client.BankClient", b =>
                {
                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("IdentityCard")
                        .IsRequired();

                    b.Navigation("PartialPasswords");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
